spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
#logging:
#  level:
#    root: DEBUG
#server:
#  port: 8181